### ISSUE TITLE
change name and logo on tab preview

### ISSUE THREAD

**Issue by Kamalisham98** [amalananda/Mobile-Legends#2]
## Context
currently our title on malls project still using default name and logo react App project.

<img width="280" alt="image" src="https://github.com/amalananda/Mobile-Legends/assets/71475248/92ebdd53-0eff-4c33-bcdf-70d732018740">

## Task 
- rename it to `Mall's` or `Mall's Game`
- try to change logo with emoji first, or any image except current logo

**Comment by amalananda** [comment]
push on master
